backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'links'
    label: 'Links'
    editor:
      preview: false
    files:
      - label: 'Links'
        name: 'links'
        file: '_data/links.yml'
        fields:
          - label: 'Link Title'
            name: 'link_title'
            widget: 'string'
            fields:
              - { label: Link Title, name: link_title, widget: string }
              - { label: Link Url, name: link_url, widget: string }