backend:
  name: git-gateway
  branch: with-cms # Branch to update (optional; defaults to master)
media_folder: 'assets/'
collections:
- name: 'config'
  label: 'Settings and Links'
  editor:
    preview: false
  files:
    - label: 'Manage Links'
      name: 'links'
      file: '_data/links.yml'
      fields:
        - label: 'Links'
          name: 'links'
          widget: 'list'
          fields:
            - { label: Link Title, name: link_title, widget: string }
            - { label: Link URL, name: link_url, widget: string }
    - label: 'Edit Profile'
      name: 'profile'
      file: '_data/profile.yml'
      fields:
        - label: 'Site Title'
          name: 'title'
          widget: 'string'
          fields:
            - { label: Site title, name: title, widget: string }
        - label: 'Site Footer'
          name: 'footer'
          widget: 'string'
          fields:
            - { label: Footer Text, name: footer, widget: text }
        - label: 'Display Name'
          name: 'display_name'
          widget: 'string'
          fields:
            - { label: Display Name, name: display_name, widget: string }
        - label: 'Profile Picture'
          name: 'profile_pic'
          widget: 'image'
          fields:
            - { label: Profile Picture, name: profile_picture, widget: image }
        - label: 'Bio'
          name: 'bio'
          widget: 'string'
          fields:
            - { label: Bio, name: bio, widget: text }
        - label: 'Website URL'
          name: 'website'
          widget: 'string'
          fields:
            - { label: Website URL, name: website, widget: text }
        - label: 'Email'
          name: 'email'
          widget: 'string'
          fields:
            - { label: Email, name: email, widget: text }
        - label: 'Facebook'
          name: 'Facebook URL'
          widget: 'string'
          fields:
            - { label: Facebook URL, name: facebook, widget: text }
        - label: 'Twitter URL'
          name: 'twitter'
          widget: 'string'
          fields:
            - { label: Twitter URL, name: twitter, widget: text }
        - label: 'LinkedIn URL'
          name: 'linkedin'
          widget: 'string'
          fields:
            - { label: LinkedIn URL, name: linkedin, widget: text }
        