backend:
  name: git-gateway
  branch: with-cms # Branch to update (optional; defaults to master)
media_folder: 'assets/'
collections:
- name: 'config'
  label: 'Config'
  editor:
    preview: false
  files:
    - label: 'Links'
      name: 'links'
      file: '_data/links.yml'
      fields:
        - label: 'Links'
          name: 'links'
          widget: 'list'
          fields:
            - { label: Link Title, name: link_title, widget: string }
            - { label: Link Url, name: link_url, widget: string }
    - label: 'Profile'
      name: 'profile'
      file: '_data/profile.yml'
      fields:
        - label: 'Site Title'
          name: 'title'
          widget: 'string'
          fields:
            - { label: Site title, name: title, widget: string }
        - label: 'Site Footer'
          name: 'footer'
          widget: 'string'
          fields:
            - { label: Footer Text, name: footer, widget: text }
        - label: 'Display Name'
          name: 'display_name'
          widget: 'string'
          fields:
            - { label: Display Name, name: display_name, widget: string }
        