backend:
  name: git-gateway
  branch: with-cms # Branch to update (optional; defaults to master)
media_folder: 'assets/'
collections:
 - name: links
    label: Links
    files:
      - file: data/links.yml
        label: Links
        name: links
        fields:
          - label: Links
            name: links
            widget: string
            fields:
              - {label: Link Title, name: link_title, widget: string}
              - {label: Link Url, name: link_url, widget: string}
        